### ISSUE TITLE
Evaluator Meta Issue

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#22]
I have a first working implementation but there is still some work to get a "usable" kernel.

Here are the important issues that need to be fixed : 

- [ ] #18 : Multiple lines prompted into the client in jupyter console
- [ ] #19 : Remove annoying warnings
- [x] #20 : Can't execute code after error
- [ ] #21 : Kernel not working in lab but working in notebook and console
- [ ] #23 : Don't display the "Out" cell when result is null

Once those critical issues are fixed I can start focus on fun features : https://github.com/hadim/scijava-jupyter-kernel/issues?q=is%3Aissue+is%3Aopen+label%3APriority%3AMedium

@ctrueden If you have sometime to try it that woul be appreciated. Your input is always super helpful :-)

**Comment by hadim** [comment]
Also for now Beaker need to be installed manually : 

```bash
https://github.com/twosigma/beakerx.git
cd beakerx/kernel/base/
gradle publishToMavenLocal
```

That will install everything you need in your local Maven repo.

**Comment by hadim** [comment]
Most of the issue here are or fixed or need and upstream fix and are also non-blocking issue. So I will downgrade their priorities to Medium.
